### PR TITLE
osmnx changed their branch naming scheme

### PR DESCRIPTION
**Pull request by davidbradway**

### CODE REVIEW

**Comment by matejker** [comment]
Thanks @davidbradway, nice catch!

**Comment by davidbradway** [comment]
@matejker I'm having trouble getting the environment set up right. I might ping you again for help with packages.

**Comment by matejker** [comment]
Yeah, sure feel free to ask here / mail. I just did `pip freeze` on my local virtual env (`Python 3.6.9`), maybe it will help
```
appnope==0.1.0
attrs==19.3.0
backcall==0.2.0
bleach==3.1.5
certifi==2020.6.20
chardet==3.0.4
click==7.1.2
click-plugins==1.1.1
cligj==0.5.0
cycler==0.10.0
decorator==4.4.2
defusedxml==0.6.0
descartes==1.1.0
entrypoints==0.3
Fiona==1.8.13.post1
geopandas==0.8.0
idna==2.10
importlib-metadata==1.7.0
ipykernel==5.3.2
ipython==7.16.1
ipython-genutils==0.2.0
jedi==0.17.1
Jinja2==2.11.2
jsonschema==3.2.0
jupyter-client==6.1.6
jupyter-core==4.6.3
kiwisolver==1.2.0
MarkupSafe==1.1.1
matplotlib==3.2.2
mistune==0.8.4
mk-network==0.0.4
munch==2.5.0
nbconvert==5.6.1
nbformat==5.0.7
networkx==2.4
notebook==6.0.3
numpy==1.19.0
osmnx==0.15.1
packaging==20.4
pandas==1.0.5
pandocfilters==1.4.2
parso==0.7.0
pexpect==4.8.0
pickleshare==0.7.5
prometheus-client==0.8.0
prompt-toolkit==3.0.5
ptyprocess==0.6.0
Pygments==2.6.1
pyparsing==2.4.7
pyproj==2.6.1.post1
pyrsistent==0.16.0
python-dateutil==2.8.1
pytz==2020.1
pyzmq==19.0.1
requests==2.24.0
Rtree==0.9.4
Send2Trash==1.5.0
Shapely==1.7.0
six==1.15.0
terminado==0.8.3
testpath==0.4.4
tornado==6.0.4
traitlets==4.3.3
urllib3==1.25.9
wcwidth==0.2.5
webencodings==0.5.1
zipp==3.1.0
```

**Comment by davidbradway** [comment]
Thanks for the details. One more patch coming for that requirements.txt file in a moment.
I'm hitting this problem with Fiona below, so I might try again in WSL or Linux.
https://stackoverflow.com/questions/50876702/cant-install-fiona-on-windows

**Comment by davidbradway** [comment]
Still having troubles with `pip install -r requirements.txt`
```
Obtaining network from git+git://github.com/matejker/network@master#egg=network (from -r requirements.txt (line 2))
  Cloning git://github.com/matejker/network (to revision master) to ./venv/src/network
  Running command git clone -q git://github.com/matejker/network /home/dpb6/everystreet/venv/src/network
  WARNING: Generating metadata for package network produced metadata for project name mk-network. Fix your #egg=network fragments.
WARNING: Discarding git+git://github.com/matejker/network@master#egg=network. Requested mk-network from git+git://github.com/matejker/network@master#egg=network (from -r requirements.txt (line 2)) has inconsistent name: filename has 'network', but metadata has 'mk-network'
ERROR: Could not find a version that satisfies the requirement network (unavailable) (from versions: 0.1)
ERROR: No matching distribution found for network (unavailable)
```

**Comment by matejker** [comment]
Ah maybe `-e git://github.com/matejker/network@master#egg=mk-network`

**Comment by davidbradway** [comment]
One more question for now, what kind of architecture are you running on?
Windows, Mac or Linux?

**Comment by davidbradway** [comment]
Nevermind. I got it to work using Docker. Let me know if you want my Dockerfile for this repo. Thanks for your help. Great work on the app and PDF write-up!

**Comment by matejker** [comment]
Ah sorry, yeah I tested is on it both on Mac and Linux (+Docker), the web service is basically a dockerized flask app.

Thanks glad to hear that :) Good luck with all the running, what city do you run?

**Comment by matejker** [comment]
Oh wow, thats really cool! Did you use the app for generating the routes?

**Comment by davidbradway** [comment]
To be honest, I played around with your web UI and today I used the Jupyter
notebook to look at "Old West Durham, Durham, North Carolina", but I mostly
laid out my routes by hand using Garmin Connect one one screen and my
CityStrides nodes on another screen.

**Comment by matejker** [comment]
Yeah, it makes sense :) I find out that the algorithm "optimal" route isn't necessarily the most _human runnable_ way. I think when you read the PDF / understand the algorithm you can easily make a near optimal route which is much better.

**Pull request merged**
